# Generated by Django 5.1.7 on 2025-04-08 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Consulta Veterinaria', 'Consulta Veterinaria'), ('Baño y Peluquería', 'Baño y Peluquería'), ('Vacunación', 'Vacunación'), ('Telemedicina', 'Telemedicina')], max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.mascota')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
