# Generated by Django 5.2 on 2025-06-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_cita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
